### ISSUE TITLE
Content-Type header is mandatory for Express to handle the body data

### ISSUE THREAD

**Issue by WINOFFRG** [WINOFFRG/widevine-license-proxy-server-nodejs#1]
Currently, I am using a Raw body parser in Express for `application/octet-stream` and my code works fine. And for that to work, I always need to add `Content-Type : Application/Octet-Stream` header when I request a license from the player. This causes a lot of trouble on the frontend side. 
Need some help in debugging the ExpressJS Code to get rid of that header.

**Comment by joeyparrish** [comment]
If you don't want the client to have to send a specific content-type, try setting your body-parser type to `*/*`.  Does this work?

**Comment by joeyparrish** [comment]
Oh, found an even better option from [the docs](https://github.com/expressjs/body-parser#type-1):

> The type option is used to determine what media type the middleware will parse. This option can be a string, array of strings, or a function. ... If a function, the type option is called as fn(req) and the request is parsed if it returns a truthy value.

So you should be able to do this:

```js
app.use(bodyParser.raw({
  type: (req) => true,  // Accept all requests, regardless of type
});
```

**Comment by WINOFFRG** [comment]
Sorry, already tried that. Doesn't work. If I set the type to `*/*` then also I'm forced to attach `Content-Type` header from the frontend. Currently, 
```
app.use(bodyParser.raw({
    type:"*/*"
}));
```
If no header for `Content-Type` is sent from the frontend it fails to parse the data in the license body and sets it to an empty JSON object. 

![image](https://user-images.githubusercontent.com/61311751/136576218-1aa7ae90-1e41-4f6c-93c3-4ca60ec9e8fa.png)

**Comment by joeyparrish** [comment]
What about using the callback style instead of a string?

```js
app.use(bodyParser.raw({
  type: (req) => true,  // Accept all requests, regardless of type
});
```

Does this work?
